const PRODUCT = {
  FETCH_PENDING: 'FETCH_PENDING_PRODUCT',
  FETCH_SUCCESS: 'FETCH_PENDING_SUCCESS',
  FETCH_ERROR: 'FETCH_PENDING_ERROR'
}

const PURCHASED = {
  PENDING: 'PURCHASED_PENDING',
  SUCCESS: 'PURCHASED_SUCCESS',
  ERROR: 'PURCHASED_ERROR'
}

export {
  PRODUCT,
  PURCHASED
}