const PRODUCT = {
  FETCH_PENDING: 'FETCH_PENDING_PRODUCT',
  FETCH_SUCCESS: 'FETCH_PENDING_SUCCESS',
  FETCH_ERROR: 'FETCH_PENDING_ERROR'
}

const PURCHASED = {
  SUCCESS: 'PURCHASED_SUCCESS'
}

const WISHLIST = {
  SUCCESS: 'WISHLIST_SUCCESS'
}

export {
  PRODUCT,
  PURCHASED,
  WISHLIST
}